In [1]:
import numpy as np
import mathplotlib.pyplot.py
import pandas as pd
import dataset as sns
dataset=dataset_cancer('cancer.csv')
cancer=dataset.variety[:,:4]

ModuleNotFoundError: No module named 'mathplotlib'

In [12]:
import numpy as np
import mathplotlib.pyplot.py
import pandas as pd
import dataset as sns
irist=dataset_iris('iris.csv')
iris=dataset.variety[:,4]


ModuleNotFoundError: No module named 'mathplotlib'

In [11]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy =accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)


SyntaxError: invalid syntax (651642041.py, line 1)

In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv('iris.csv')
dataset.head()
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values
print("X Values:\n",x)
print("Y Values:\n",y)

X Values:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy =accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)



NameError: name 'X' is not defined

In [15]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy =accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)


NameError: name 'classifier' is not defined